config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'landing_pages#index'
  resources :videos
  namespace :owner do
    resources :lyrics
  end 
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lyric.rb
class Lyric < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :lyrics, dependent: :destroy
  has_many :videos, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_video.rb
class UserVideo < ApplicationRecord
  belongs_to :user
end

app/models/video.rb
class Video < ApplicationRecord
  mount_uploader :image, ImageUploader
  mount_uploader :video, VideoUploader
  
  belongs_to :user

  validates :title, presence: true
  validates :artist, presence: true
  validates :video, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/landing_pages_controller.rb
class LandingPagesController < ApplicationController

  def index
    
  end
end

app/controllers/owner/lyrics_controller.rb
class Owner::LyricsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @lyrics = Lyric.all
    @lyrics = Lyric.order("title").page(params[:page]).per_page(6)
  end

  def new
    @lyric = Lyric.new
  end

  def create
    lyric_create_params = lyric_params
    lyric_create_params["video_url"] = generate_embeddable_video_url(lyric_params["video_url"])
    @lyric = current_user.lyrics.create(lyric_create_params)  
    redirect_to owner_lyric_path(@lyric)
  end

  def show
    @lyric = Lyric.find(params[:id])
  end

  def edit
    @lyric = Lyric.find(params[:id])
  end

  def destroy
    @lyric = Lyric.find(params[:id])
    @lyric.destroy
    redirect_to root_path
  end

  private

  def generate_embeddable_video_url(video_url)
    # input from the form
    # video_url = "https://www.youtube.com/watch?v=ZCEYsOqEz_U"
    uri    = URI.parse(video_url)
    params = CGI.parse(uri.query)
    # parse the query params to get the video id
    video_id = params['v'].first
    return "https://www.youtube.com/embed/#{video_id}"
  end

  def lyric_params
    params.require(:lyric).permit(:title, :artist, :video_url)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @lyric = Lyric.find(params[:id])
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_user!
  

  def index
    @videos = Video.all
    @videos = Video.order("title").page(params[:page]).per_page(6)
  end

  def new
    @video = Video.new
  end


  def create
    @video = current_user.videos.create(video_params)
    if @video.valid?
      redirect_to video_path(@video)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
   
  end

  private

  helper_method :current_user_video
  def current_user_video
    @current_user_video ||= Video.find(params[:id])
  end

  def video_params
    params.require(:video).permit(:title, :artist, :image, :video)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_pages_helper.rb
module LandingPagesHelper
end

app/helpers/owner/lyrics_helper.rb
module Owner::LyricsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/landing_pages/index.html.erb
<div class="hero">
  <br />
  <div class="sing ">
    <h1>What Are You Waiting For?</h1>
    
    <h2>These Songs Won't Sing Themselves</h2>
    <%= link_to "Let's Sing!", owner_lyrics_path, class: 'btn btn-primary' %> 

    <%= link_to "Get Inspired", videos_path, class: 'btn btn-primary' %>

    
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Singwithme</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="http://vjs.zencdn.net/5.12.6/video-js.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Righteous|Rye&display=swap" rel="stylesheet">
  </head>

  <body>
    <div id="flex-content-container">
      <nav class="navbar navbar-toggleable-md navbar-inverse bg-primary">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <%= link_to 'SingWithMe', root_path, class: 'navbar-brand' %>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav mr-auto mt-2 mt-md-0">
            <li class="nav-item active">
              <%= link_to owner_lyrics_path, class: 'nav-link' do %>
                <i class="fa fa-microphone"></i>Lyrics
              <% end %>
            </li>

            <li class="nav-item">
              <%= link_to 'Inspiration', videos_path, class: 'nav-link' %>
            </li>
          </ul>

          <ul class="navbar-nav">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to 'My Profile', user_path(current_user), class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
              </li>
              <% else %>
              <li class="nav-item">
                <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
              </li>
            <% end %>
          </div>
        </nav>

        <% if notice.present? %>
          <p class="alert alert-info"><%= notice %></p>
        <% end %>
        <% if alert.present? %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>

        <%= yield %>
      </div>


      <div id="footer">
        <div class="container">
          <div class="row">
            <div class="col-12 col-sm-3">
              <b>Owner</b>
              <br />
              <%= link_to 'Upload A Video', new_owner_lyric_path %>
              </div>
              <br />
              <div class="col-12 col-sm-3 social">
              <b>Singers</b>
              <br />
              <%= link_to 'Show Off Your Skills', new_video_path %>
              </div>
              <div class="col-12 col-sm-3 social">
              123 Karoake Sing Rd. Microphone City, TX 72132
              <br />
              </div>
              <div class="social col-12 col-sm-3 float-right">
                <%= link_to 'https://twitter.com/CantaloupesD' do %>
                  <span class="fa fa-twitter-square fa-2x social-button"></span>
                <% end %>
                <%= link_to 'https://github.com/lonier4/singwithme' do %>
                  <span class="fa fa-github-square fa-2x social-button"></span>
                <% end %>
              </div>
            </div>
          </div>   
        </div>

        <script src="http://vjs.zencdn.net/5.12.6/video.js"></script>
        <script src="http://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
      </body>
    </html>

app/views/owner/lyrics/index.html.erb
<br />
<div class="container">
  <div class="row text-center">
    <% @lyrics.each do |lyric| %>
      <div class="col-sm">
        <iframe
          width="340"
          height="180"
          src="<%= lyric.video_url %>"
          frameborder="0"
          allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
          allowfullscreen>
        </iframe>
        
        <div class="col-sm text-center">
          <%= link_to lyric.title, owner_lyric_path(lyric) %> -
          <%= link_to lyric.artist, owner_lyric_path(lyric) %>
        
          
            </div>
          </div>
        
      <% end %>
    </div>
  </div>
</div> 

<%= will_paginate @lyrics, previous_label: h("<<"), next_label: h(">>") %>


app/views/owner/lyrics/new.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1>Add a new Video</h1>
  <%= simple_form_for @lyric, url: owner_lyrics_path  do |f| %>
    <%= f.input :title %>
    <%= f.input :artist %>
    <%= f.input :video_url %>
    <br />
    <%= f.submit "Create", class: 'btn btn-primary' %>
    <br />
  <% end %>
  <br />
</div>

app/views/owner/lyrics/show.html.erb
<br />
<div class="booyah-box col-8 offset-2">
  <div class="col-sm text-center">
    <iframe
      width="460"
      height="260"
      src="<%= @lyric.video_url %>"
      frameborder="0"
      allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
      allowfullscreen>
    </iframe>
    <h2 class="text-center">
      <%= @lyric.title %> 
      -
      <%= @lyric.artist %>
    </h2>
    <% if current_user && current_user == @lyric.user %>
      <%= link_to 'Destroy', owner_lyric_path(@lyric), method: :delete, data: {confirm: 'Ready to part ways with this video?'}, class: 'btn btn-primary btn-sm' %>
      <% end %>
    </div>
  </div>

app/views/users/show.html.erb
<div class="booyah-box col-10 offset-1">
  <div class="row text-center">
    <div class="col">
      <h1>My Profile</h1>
    </div>
  </div>
  </br>

  <div class="row">
    <div class="col">
      <h2><%= @user.email %></h2>
    </div>
    <div class="col">
      <h2>Singing Since: <%= @user.created_at.strftime("%B %d, %Y") %></h2>
    </div>
  </div>
  <div class="clr"></div>
  </br>

  <h2 class="text-center">My Lyrics</h2>
    <div class="container">
      <div class="row text-center">
        <% @user.lyrics.each do |lyric| %>
          <div class="col-sm">
            <iframe
              width="340"
              height="180"
              src="<%= lyric.video_url %>"
              frameborder="0"
              allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen>
            </iframe>
            
            <div class="col-sm text-center">
              <%= link_to lyric.title, owner_lyric_path(lyric) %> -
              <%= link_to lyric.artist, owner_lyric_path(lyric) %>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    </br>

    <h2 class="text-center">My Stellar Performances</h2>
      <div class="container">
        <div class=" row text-center">
          <% @user.videos.each do |video| %>
            <div class="col-sm">
              <video id="my-video" class="video-js vjs-big-play-centered" controls preload="auto" width="340" height="180"
               poster="<%= image_path('black.jpg') %>" data-setup="{}">
              <source src="<%= video.video.to_s %>" type='video/mp4'>
              <source src="<%= video.video.to_s %>" type='video/webm'>
              <noscript>
                <p class="vjs-no-js">
                  To view this video please enable JavaScript, and consider upgrading to a web browser that
                <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
                </p>
              </noscript>
            </video>
            
            <div class="col-sm text-center">
              <%= link_to video.title, video_path(video) %>
              -
              <%= link_to video.artist, video_path(video) %>
            </div>
          </div>
        <% end %>
        <br clear="clr" />
      </div>
    </div>
  </div> 
    

app/views/videos/index.html.erb
<br />
  <div class="booyah-box col-10 offset-1">
    <h1 class="text-center">Checkout Some Performances</h1>
    <hr />
    <h6 class="text-center">Sometimes we just have to watch other humans sing first so we can warm up. Psst..Tequila always helps too!</h6>
    </br>
    
    <div class="container">
      <div class=" row text-center">
        <% @videos.each do |video| %>
          <div class="col-sm">
            <video id="my-video" class="video-js vjs-big-play-centered" controls preload="auto" width="340" height="180"
             poster="<%= image_path('black.jpg') %>" data-setup="{}">
            <source src="<%= video.video.to_s %>" type='video/mp4'>
            <source src="<%= video.video.to_s %>" type='video/webm'>
            <noscript>
              <p class="vjs-no-js">
                To view this video please enable JavaScript, and consider upgrading to a web browser that
              <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
              </p>
            </noscript>
          </video>
          </br>
          <div class="col-sm text-center">
            <%= link_to video.title, video_path(video) %>
            -
            <%= link_to video.artist, video_path(video) %>
          </div>
        </div>
      <% end %>
      <br clear="clr" />
    </div>
  </div>
</div>

<%= will_paginate @videos, previous_label: h("<<"), next_label: h(">>") %>

  

app/views/videos/new.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1>Share Your Best Performance</h1>
  <%= simple_form_for @video do |f| %>
    <%= f.input :title %>
    <%= f.input :artist %>
    <%= f.input :video %>
    <br />
    <%= f.submit "Add Your Video", class: 'btn btn-primary' %>
    <br />
  <% end %>
  <br />
</div>

app/views/videos/show.html.erb
<br />
  <div class="booyah-box col-8 offset-2">
    <div class="text center">
      <video id="my-video" class="video-js vjs-big-play-centered" controls preload="auto" width="990" height="700"
      poster="<%= image_path('black.jpg') %>" data-setup="{}">
        <source src="<%= current_user_video.video.to_s %>" type='video/mp4'>
        <source src="<%= current_user_video.video.to_s %>" type='video/webm'>
          <noscript>
            <p class="vjs-no-js">
              To view this video please enable JavaScript, and consider upgrading to a web browser that
              <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
            </p>
          </noscript>
          </video>
          </br>
          <h4>
            <%= current_user_video.title %> 
            -
            <%= current_user_video.artist %>
          </h4> 
        </div>
      </div>
      </br>
    </div>
  </div>
</div>

  
